In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.layers import GRU
from tensorflow.keras.models import load_model
import string

In [2]:
# Reading corpus the text file
with open("E:\\vshl\\Engg 5th Sem\\Machine Learning\\ML2\\data.txt", 'r', encoding='utf-8') as myfile:
    mytext = myfile.read()

In [3]:
mytext

'Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country\'s partnership with India among the "most consequential in the world". The BBC\'s Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit\'s potential in strengthening the ties between the two nations.\n\nThe US\'s relationship with India - the world\'s most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.\n\nThe remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.\n\nA key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China\'s growing influence in the Indo-Pacifi

In [4]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index) + 1

In [5]:
mytokenizer.word_index

{'the': 1,
 'and': 2,
 'of': 3,
 'a': 4,
 'in': 5,
 'to': 6,
 'as': 7,
 'is': 8,
 'was': 9,
 'with': 10,
 'for': 11,
 'by': 12,
 'it': 13,
 'her': 14,
 'that': 15,
 'on': 16,
 'their': 17,
 'she': 18,
 'are': 19,
 'his': 20,
 'he': 21,
 'or': 22,
 'at': 23,
 'an': 24,
 'from': 25,
 'its': 26,
 'they': 27,
 'india': 28,
 'has': 29,
 'engineering': 30,
 'be': 31,
 'this': 32,
 'but': 33,
 'one': 34,
 'had': 35,
 'also': 36,
 'freedom': 37,
 'which': 38,
 'were': 39,
 'cricket': 40,
 'other': 41,
 'life': 42,
 'people': 43,
 'not': 44,
 'been': 45,
 'country': 46,
 'who': 47,
 'have': 48,
 'each': 49,
 'such': 50,
 'more': 51,
 'first': 52,
 'most': 53,
 'can': 54,
 'into': 55,
 'day': 56,
 'tom': 57,
 'mr': 58,
 'through': 59,
 'about': 60,
 'us': 61,
 'between': 62,
 'two': 63,
 'fighters': 64,
 'some': 65,
 'new': 66,
 'there': 67,
 'many': 68,
 'known': 69,
 'university': 70,
 'up': 71,
 'all': 72,
 'when': 73,
 'became': 74,
 'used': 75,
 'may': 76,
 'small': 77,
 'century': 78,
 'co

In [6]:
my_input_sequences = []
for line in mytext.split('\n'):
    #print(line)
    token_list = mytokenizer.texts_to_sequences([line])[0]
    #print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        #print(input_sequences)

In [7]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [8]:
input_sequences[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [9]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [10]:
X[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 240,   4])

In [11]:
y

array([   4, 2062,  132, ...,    6, 4658, 4659])

In [14]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [15]:
y[1]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [14]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(300, return_sequences=True))  # Return sequences for stacking
model.add(GRU(300))
model.add(Dense(total_words, activation='softmax'))

In [15]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=25, verbose=1)


Epoch 1/25


572/572 [==============================] - 400s 691ms/step - loss: 7.3656 - accuracy: 0.0570
Epoch 2/25
572/572 [==============================] - 402s 704ms/step - loss: 6.7738 - accuracy: 0.0776
Epoch 3/25
572/572 [==============================] - 359s 627ms/step - loss: 6.4532 - accuracy: 0.0918
Epoch 4/25
572/572 [==============================] - 435s 761ms/step - loss: 6.1269 - accuracy: 0.0984
Epoch 5/25
572/572 [==============================] - 418s 731ms/step - loss: 5.6530 - accuracy: 0.1106
Epoch 6/25
572/572 [==============================] - 466s 815ms/step - loss: 4.9707 - accuracy: 0.1323
Epoch 7/25
572/572 [==============================] - 494s 864ms/step - loss: 4.1487 - accuracy: 0.1912
Epoch 8/25
572/572 [==============================] - 366s 641ms/step - loss: 3.3086 - accuracy: 0.3205
Epoch 9/25
572/572 [==============================] - 364s 636ms/step - loss: 2.5721 - accuracy: 0.4570
Epoch 10/25
572/572 [==============================] - 431s 7

In [14]:
model.save("my_new_model_25.h5")
#model = load_model("my_model_30.h5")

NameError: name 'model' is not defined

In [12]:
model = load_model("my_new_model_25.h5")

In [19]:
input_text = "KLE"
predict_next_words= 15


for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[110]
1/1 [==============================] - 0s 67ms/step
[110, 298]
1/1 [==============================] - 0s 62ms/step
[110, 298, 3070]
1/1 [==============================] - 0s 63ms/step
[110, 298, 3070, 7]
1/1 [==============================] - 0s 62ms/step
[110, 298, 3070, 7, 1046]
1/1 [==============================] - 0s 77ms/step
[110, 298, 3070, 7, 1046, 222]
1/1 [==============================] - 0s 81ms/step
[110, 298, 3070, 7, 1046, 222, 770]
1/1 [==============================] - 0s 83ms/step
[110, 298, 3070, 7, 1046, 222, 770, 11]
1/1 [==============================] - 0s 78ms/step
[110, 298, 3070, 7, 1046, 222, 770, 11, 3071]
1/1 [==============================] - 0s 83ms/step
[110, 298, 3070, 7, 1046, 222, 770, 11, 3071, 3072]
1/1 [==============================] - 0s 87ms/step
[110, 298, 3070, 7, 1046, 222, 770, 11, 3071, 3072, 749]
1/1 [==============================] - 0s 70ms/step
[110, 298, 3070, 7, 1046, 222, 770, 11, 3071, 3072, 749, 5]
1/1 [=====================

In [20]:
input_text = "In economics, inflation is a general increase in the"
predict_next_words= 12

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 165, 100)          466000    
                                                                 
 lstm (LSTM)                 (None, 165, 300)          481200    
                                                                 
 gru (GRU)                   (None, 300)               541800    
                                                                 
 dense (Dense)               (None, 4660)              1402660   
                                                                 
Total params: 2891660 (11.03 MB)
Trainable params: 2891660 (11.03 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
